### ISSUE TITLE
Barcode scanner for login isn't loading properly

### ISSUE THREAD

**Issue by jamesnw** [other-realm/rcredits-mobile#2]
On iOS, clicking the "Scan to sign in" button doesn't load the scanner. The loader spinner just spins indefinitely. If you leave the app and come back, then it will appear. 

It appears that it's called inside a `$ionicPlatform.ready()` function, so I'm guessing it has something to do with when that is being called.

**Comment by TheOtherRealm** [comment]
Hmm, I can't repeat the issue on my android phone or in the chrome
browser.  In the desktop browser, I need to enable cross-origin resource
sharing in order to do a transaction (because the server is localhost)
but that is only on the desktop and only for customer transactions.  I
know that trying to get the app to work in a browser that does not use
WebSQL does not work (at some point we need to rewrite the code to use
the non-obsolete IndexedDB, probably will do this at the same time as I
make the app not use Ionic/angular - but that is basically starting from
scratch) but in Firefox anyway, the error message is: Error: this.db is
null .  Do you have the complete stack trace?
Unrelated, but I found a bug in the undo button that makes it not go
away when clicked. Clicking it twice redoes the transaction and doing a
third time undoes the transaction again. It should be a simple fix.

Aaron E-J
Other Realm LLC
http://otherrealm.org
http://theotherrealm.org (Blog)

**Comment by jamesnw** [comment]
The error I'm seeing is `Refused to load gap://ready because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.`

This led me to https://github.com/ionic-team/ionic/issues/6928. I did a bit of troubleshooting based on that thread, but wasn't able to get it to work.

**Comment by TheOtherRealm** [comment]
Hi James,
This is a probably a CORS (Cross Origin Resource Sharing) issue, I
tweaked the CORS header in index.html and the config files but I have no
idea if this will work on your iOS phone, did you simply use|ionic run
ios| or did you add a |-l| ?  There shouldn't be any CORS issues on
phones, but then again, I have never tried it on an iphone.  In Chrome
(|ionic serve)|,  use this extension:
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog
.  Without this, the app won't except transactions in the browser.  Hope
this helps.

Aaron E-J
Other Realm LLC
http://otherrealm.org
http://theotherrealm.org (Blog)

**Comment by jamesnw** [comment]
Hmm, I'm still seeing the same behavior. Oddly, when I inspect the iOS app using Safari, the changed meta header does not carry over. I've rebuilt using `ionic cordova build ios` and even deleted the ios build folder completely and rebuilt. That line in the source index.html is:

 `<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:* http://10.0.0.7:* http://127.0.0.1:* ; default-src *; media-src *; img-src * blob: data:; style-src * 'unsafe-inline'; ">`

There's no mention of the gap://ready.

Are there any plugins that are overwriting this somewhere?

**Comment by TheOtherRealm** [comment]
Hmmm, did you update the repository with the changes I made?  I have no
idea whether that would solve the problem, but it's the first step. 

I changed the Content-Security-Policy meta header slightly:


-  <meta http-equiv="Content-Security-Policy" content="script-src 'self'
'unsafe-inline' 'unsafe-eval' http://localhost:* http://10.0.0.7:*
http://127.0.0.1:* ; default-src *; media-src *; img-src * blob: data:;
style-src * 'unsafe-inline'; ">

+  <meta http-equiv="Content-Security-Policy" content="script-src *
'unsafe-inline' 'unsafe-eval' http://localhost:* http://10.0.0.7:*
http://127.0.0.1:* ; default-src * gap://ready; media-src *; img-src *
blob: data:; style-src * 'unsafe-inline';
https://stage-new.rcredits.org/pos">

And the config.xml file:

-  <access origin="*"/>

+  <access origin='*' allows-arbitrary-loads-in-media='true'
allows-arbitrary-loads-in-web-content='true'
allows-local-networking='true' />

+  <allow-navigation href="*"/>

+  <allow-navigation href="http://*/*"/>

+  <allow-navigation href="https://*/*"/>

+  <allow-navigation href="data:*"/>

||||||

Aaron E-J
Other Realm LLC
http://otherrealm.org
http://theotherrealm.org (Blog)

**Comment by jamesnw** [comment]
Ok, I managed to build it correctly, and it's working now. It took just the right combination of removing the ios platform, re-adding it, regenerating resources, etc. I think I'm on a newer version of ionic, which also made it a bit tricky.

**Comment by TheOtherRealm** [comment]
Did you also update to the latest revision?  In addition to CORS
changes, there were some bug fixes and other minor changes.

Aaron E-J
Other Realm LLC
http://otherrealm.org
http://theotherrealm.org (Blog)

**Comment by WilliamSpademan** [comment]
Wow, great news! Thanks!

If you got it working on a more recent version of Ionic, we should probably
switch to that platform, so we keep up with the times.

—
*William Spademan*
Executive Director


*Common Good™*
*the payment card for community power*

CommonGood.earth <http://commongood.earth/>
+1 413 628 1723 office
+1 413 628 1021 direct line
PO Box 21, Ashfield, MA 01330 USA

**Comment by TheOtherRealm** [comment]
The issue with doing that is, it is a whole other version and it would
entail essentially starting from scratch because this version uses
Angular 2, and Angular 2 is basically an entirely framework then version
1.  I think we should get this version working, then see whether
sticking with Ionic makes sense.

Aaron E-J
Other Realm LLC
http://otherrealm.org
http://theotherrealm.org (Blog)

On 2017-07-01 2:42 PM, William Spademan wrote:
> Wow, great news! Thanks!
>
> If you got it working on a more recent version of Ionic, we should
> probably
> switch to that platform, so we keep up with the times.
>
> —
> *William Spademan*
> Executive Director
>
>
> *Common Good™*
> *the payment card for community power*
>
> CommonGood.earth <http://commongood.earth/>
> +1 413 628 1723 office
> +1 413 628 1021 direct line
> PO Box 21, Ashfield, MA 01330 USA
>
>
>

**Comment by jamesnw** [comment]
Sorry, looking at it, I think I'm on the version of ionic defined by bower. Sorry for the confusion!

**Comment by TheOtherRealm** [comment]
Alright, I tried installing things in a Linux environment and realized
there was a lot of the setup process that needed tweaking - the setup
process /should/ go slightly more smoothly... should...

Aaron E-J
Other Realm LLC
http://otherrealm.org
http://theotherrealm.org (Blog)
